# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b97d4157c59481b37bba40c3ebe926f0214c57ae114822efd30c3ed096c6faf2277b29f5cd45ba3db740251b3e6c935501f37a423557836ef95fc1cf21b0c3e

test:
  secret_key_base: 1bd1638b58cfe749c9892d987a5938480476a2ddf597992f6733f9e1fbee8f80298664afb64a7e12ab8f48e3197ef05968d9ad3f580550d2ace86206d4159bb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
